// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: NullRequest.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GrpcServerImpl {
  /// <summary>
  /// The service definition.
  /// </summary>
  public static partial class HelloNullGrpc
  {
    static readonly string __ServiceName = "GrpcServer.HelloNullGrpc";

    static readonly grpc::Marshaller<global::GrpcServerImpl.NullRequest> __Marshaller_GrpcServer_NullRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcServerImpl.NullRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GrpcServerImpl.NullReply> __Marshaller_GrpcServer_NullReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcServerImpl.NullReply.Parser.ParseFrom);

    static readonly grpc::Method<global::GrpcServerImpl.NullRequest, global::GrpcServerImpl.NullReply> __Method_SayHello = new grpc::Method<global::GrpcServerImpl.NullRequest, global::GrpcServerImpl.NullReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SayHello",
        __Marshaller_GrpcServer_NullRequest,
        __Marshaller_GrpcServer_NullReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GrpcServerImpl.NullRequestReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of HelloNullGrpc</summary>
    public abstract partial class HelloNullGrpcBase
    {
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::GrpcServerImpl.NullReply> SayHello(global::GrpcServerImpl.NullRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for HelloNullGrpc</summary>
    public partial class HelloNullGrpcClient : grpc::ClientBase<HelloNullGrpcClient>
    {
      /// <summary>Creates a new client for HelloNullGrpc</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public HelloNullGrpcClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for HelloNullGrpc that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public HelloNullGrpcClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected HelloNullGrpcClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected HelloNullGrpcClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::GrpcServerImpl.NullReply SayHello(global::GrpcServerImpl.NullRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHello(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::GrpcServerImpl.NullReply SayHello(global::GrpcServerImpl.NullRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SayHello, null, options, request);
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::GrpcServerImpl.NullReply> SayHelloAsync(global::GrpcServerImpl.NullRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHelloAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::GrpcServerImpl.NullReply> SayHelloAsync(global::GrpcServerImpl.NullRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SayHello, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override HelloNullGrpcClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new HelloNullGrpcClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(HelloNullGrpcBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SayHello, serviceImpl.SayHello).Build();
    }

  }
}
#endregion
